name: Build for Windows
on: 
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false

    steps:
    - uses: actions/checkout@v3

    - name: Set env
      run: echo "CLERIC_VERSION=v$(cat cmd/cleric/version.txt)" >> $GITHUB_ENV

    - uses: WillAbides/setup-go-faster@v1.14.0
      id: setup-go-faster
      with:
        go-version: "*"

    - name: Get dependencies
      run: sudo apt update && sudo apt install gcc xorg-dev gcc-mingw-w64


    - name: Install fyne
      run: go install fyne.io/fyne/v2/cmd/fyne@latest

    - name: Package (Windows)
      run:  cd cmd/cleric &&  CGO_ENABLED=1 CC=x86_64-w64-mingw32-gcc CXX=x86_64-w64-mingw32-g++ fyne package --release -os windows -icon  ../../assets/Icon.png  && mv cleric.exe ../../

    - uses: actions/upload-artifact@v4
      with:
        name: cleric_${{ env.CLERIC_VERSION }}_macOS_amd64
        path: |
          LICENSE
          README.md
          cleric.exe
        retention-days: 2